### ISSUE TITLE
Spyder Modelx Plug-in Not found

### ISSUE THREAD

**Issue by jjaredrides** [fumitoh/spyder-modelx#12]
## Description of your problem
Basically: spyder is unable to find the modelx plug-in.

I updated my python interpreter from anaconda to pyenv and am using virtual environments. 

I downloaded spyder (e.g, not from the anaconda prompt) and I updated my interpreter and Path to reference my specific virtual environment where modelx and spyder-modelx was downloaded to. 

The Ipython console is able to find the modelx library (e.g. no error comes up when I type "import modelx as mx")

For the PythonPath - I added a userpath that references my specific virtual environment where the modelx and spyder-modelx libraries are located.

**What steps will reproduce the problem?**

1. Go to User Module Reloader (UMR) and set UMR excluded to "modelx"
2. It says:  'the following modules are not installed on your machine: modelx
3. Modelx plug-ins are not found in the "Panes" section either

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* modelx Version: 0.21.0
* Spyder Version: 5.4.2 (it says the default python that come with spyder says 3.8.10 even though the interpreter is 3.10.9)
* Python Version: 3.10.9
* Operating system: windows 10

**Comment by jjaredrides** [comment]
Here's what happens. I think I probably need to install Spyder through PIP - via the virtual environment according to the instructions.
https://docs.spyder-ide.org/current/installation.html
```
import modelx

import spyder_modelx
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
```

**Comment by jjaredrides** [comment]
Here's what happens. I think I probably need to install Spyder through PIP - via the virtual environment according to the instructions.
https://docs.spyder-ide.org/current/installation.html
```
import modelx

import spyder_modelx
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
```

**Comment by jjaredrides** [comment]
Here's what happens. I think I probably need to install Spyder through PIP - via the virtual environment according to the instructions.
https://docs.spyder-ide.org/current/installation.html
```
import modelx

import spyder_modelx
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
```

**Comment by fumitoh** [comment]
OK then both are installed. Can you also chek if spymx-kernels is also installed?

**Comment by jjaredrides** [comment]
Yes, I see a folder for spymx_kernels.

**Comment by fumitoh** [comment]
I think spyder-modelx is not installed in the environment where Spyder is running. Did you install Spyder from the installer available from Spyder's site?

**Comment by jjaredrides** [comment]
I installed it from Spyder's website (e.g. downloaded it) vs I think I should use PIP to install it to my virtual environment.

**Comment by jjaredrides** [comment]
So what do you recommend? Should I create a new environment for Spyder modex and install Spyder in that folder? Or switch back to using Anaconda?
